### ISSUE TITLE
[Feature Request] Save compression

### ISSUE THREAD

**Issue by hyoretsu** [Cppkies-Team/Cppkies#9]
Maybe consider adding a string compression lib when saving/loading, it could do much good to some mods. This unholy save of mine <details><summary>~snip~</summary><span>Mi4wMzF8fDE2MTA2NzA4NDE1OTU7MTYxMDMzMDExODc4MjsxNjEwNzUyMzUyNDcwO2tpdHR5IHNheXNvcGVuc2VzYW1lO3l0c21rfDExMTExMTAxMTAwMTAxMTAwMTAxMHw1Ljc5MjU3NjYzODIwMDEzZSs1MTs0Ljc4ODIyNjIyMjUxNzQ0OGUrNTM7NzswOzMzNzQ0NDgwMDAwMDA2Ny44OzE7MDswOzcuMDAwMDAwMDAwMDAwMDM3ZSs1MTszOzE7MDswOy0xOzE7MDsxLjI3MjMzNjAxNjY3NjI3MmUrNDM7MTE7MDswOy0xOzA7OzEuMjI0NzI1MzkxMjE3MzY3NWUrNDQ7MTE7MTkxMjkzMTE4Mjc3MjM7MTkwNjI2NDUxNjEwNTc7NjY2NjY2NjY2NjY7MDswOy0xOy0xOy0xOy0xOy0xOzA7MDswOzA7NTA7MDswOzU3OzExMDY7MTYxMDczMjQ3NTg1ODswOzM7OzQxOzA7MDs0LjA3NjIzMzEwMzc4NjkwMmUrNDA7fDU2NSw1NjUsNi43ODIyOTI1Nzc0MDY4NDllKzQyLDAsLDAsNTY1OzcwNSw3MDUsNC4xMDQyNjQxODc0ODk0NjJlKzQyLDExLCwwLDcwNTs1MjQsNTI0LDEuMjMzOTc0NjI2NjY2NzYxNmUrMzksMTAsMTYxMDc1MjUyNTkzNDowOjE2MTA2NzA4NDE2Nzk6MDowOjA6MDowOjE2MTA2NzA4NDE2Nzk6IDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAgMDowOjE0OjM4OjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDoxNDoyMzowOjA6MDowOjA6MDowOjA6MDowOiwwLDUyNDs0MzAsNDMwLDIuMDQ1MjU1OTU5MzA4MTk5MWUrNDAsMTAsLDAsNDMwOzQ3MCw0NzAsOC43NjUyMzQ0NzAwOTU2NWUrMzksMTEsLDAsNDcwOzQ0OCw0NDgsMS4xNzA0ODM4ODk5MjU5Njg1ZSszOSwxNiwwOjA6MTowOjA6IDQ0MTY6NDo1NzoxOTI6MDowOjAhMjgxMjoyOi00MDo2NzA6MDowOjAhNDA3MToyOi0xMDoyMDU6MDowOjAhNjM0Mzo1Ojc1OjE5NDowOjA6MCE1ODQ3OjI6LTI3OjIzMDowOjA6MCE2MjU4OjI6LTYwOjQ2NDowOjA6MCE4MzEyOjU6LTcwOjUxNDowOjA6MCExMDIxNTo1Oi05MTo1Nzk6MDowOjAhMTA3NTE6NDotNDM6NDQxOjA6MDowITg0MjI6NDotMTM0OjI3NjowOjA6MCExMzI2Mzo0OjE4OjE2MjowOjA6MCExMzY4ODowOjY6MjAzOjA6MDowITE0NTMwOjE6MTY6MzkzOjA6MDowITE0OTQ4OjI6LTE1Ojc1NTowOjA6MCExNjcxMzoxOjE0OjQ4NzowOjA6MCExNjQ5NjoyOi0yOTo4OTA6MDowOjAhIDAsMCw0NDg7MzUwLDM1MCwxLjkxNjg3MTAyNjg5MDI3OWUrMzksMTAsLTEvLTEvLTEgMyAxNjEwNjcwODQxNzY0IDAsMCwzNTA7NDM4LDQzOCwxLjk0MTgzNzg4ODc4NDc2NTRlKzM5LDEwLDk2IDAgMCAwLDAsNDM4OzQxMiw0MTIsNy4zMTQyNzExNDkzMTgyNzVlKzM4LDEwLCwwLDQxMjszODUsMzg1LDEuOTI5MDQxMzAxMjIyMTQyZSszOSwxMCwsMCwzODU7MzY5LDM2OSwxLjE4NTgyOTk3NDg3NDY2NWUrNDEsMTEsLDAsMzY5OzMzNiwzMzYsMy4zMzM1MjQzNjY1NTQ5OTJlKzQwLDEwLCwwLDMzNjszMzEsMzMxLDIuMzIwNTU4Mjc1MzU0NjU1ZSs0MSwxMCwsMCwzMzE7MzExLDMxMSw4LjgxNjMzMzc4MDQ1OTE2ZSs0MSwxMCwsMCwzMTE7MjkyLDI5MiwxLjg0MDg1MTY0NjM2NDg1NjZlKzQyLDEwLCwwLDI5MjsxODIsMTgyLDIuMDUyOTg5NTEzNTAyNzE3N2UrNDIsMTAsLDAsMTgyOzIzNSwyMzUsMy41MzU0MjAxNTYxMjMxNGUrNDIsMTAsLDAsMjM1OzIwNywyMDcsMS43MjM0Nzk1ODI1NTQ3NDI0ZSs0MywxMCwsMCwyMDc7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMDExMTExMTEwMDEwMTEwMDAwMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDExMDAxMTAwMTEwMDAwMTEwMDExMTEwMDAwMTEwMDAwMDAxMTAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMDEwMTAxMDAwMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTAwMDEwMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDExMTEwMDExMDAwMDAwMDAxMTAwMTEwMDExMTExMTExMDAwMDAwMTEwMDAwMTExMTAwMDAwMDAwMTExMTExMTExMDAwMDAwMDExMDAxMTExMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMDAwMDAwMDAwMDExMTExMTAwMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMDAwMDAwMDAxMTExMTExMXwxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMTAxMTExMDAwMTAxMTEwMDExMTExMTExMTEwMDAwMTExMTExMDAxMDAxMDAwMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTAxMTExMTExMTExMTEwMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTEwMDAxMTExMTExMTExMTExMTExMDAwMDExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMDExMTExMTEwMTExMTExMTExMDExMDEwMTExMDExMDExMTExMTExMDAwMDAwMDExMTExMTExMTExMTEwMDAxMTAwMTAxMDExMTAxMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMDAxMTExMTEwMTEwMTAxMDAwMDAwMDAxMTAwMDAwMDAwMTAwMDEwMDAwMTAwMDAwMDAwMDAwMDEwMDAwMTAwMDAwMDExMTExMTEwMDAwMDAxMTExMTExMTEwMDAwMDAwfHxDb29raWUgQ2xpY2tlciBPQyBJZGVhczp7ImJvdWdodFVwZ3JhZGVzIjpbXSwidW5sb2NrZWRVcGdyYWRlcyI6W119O2NwcGtpZXM6eyJtb2RzIjp7fSwiZm9yZWlnbiI6eyJhY2hpZXZlbWVudHMiOnsiT3J0ZWlsICYgT3B0aSI6eyJ3b24iOnRydWV9LCJUaGVHTGFuZGVyIjp7IndvbiI6dHJ1ZX0sIlRoZVNrdWxseUtPIjp7IndvbiI6dHJ1ZX0sIkJvYiI6eyJ3b24iOnRydWV9LCJBdXJvcmEgTG9yZW9saXMiOnsid29uIjpmYWxzZX19LCJidWlsZGluZ3MiOnt9LCJ1cGdyYWRlcyI6eyJHb3RvIFRlc3QuLi4iOnsiYm91Z2h0Ijp0cnVlLCJ1bmxvY2tlZCI6dHJ1ZX0sIkdvdG8gVmFuaWxsYS4uLiI6eyJib3VnaHQiOnRydWUsInVubG9ja2VkIjp0cnVlfSwidGVzdCI6eyJib3VnaHQiOnRydWUsInVubG9ja2VkIjpmYWxzZX0sIkJveCBvZiBicmFuZCBiaXNjdXRzIChGYW1pbHkgU2l6ZSkiOnsiYm91Z2h0IjpmYWxzZSwidW5sb2NrZWQiOmZhbHNlfSwiQmlydGhkYXkgQ2FrZSBMb3JlbyI6eyJib3VnaHQiOmZhbHNlLCJ1bmxvY2tlZCI6ZmFsc2V9LCJNaW50IExvcmVvbCI6eyJib3VnaHQiOmZhbHNlLCJ1bmxvY2tlZCI6ZmFsc2V9LCJDaG9jb2xhdGUgTG9yZW9sIjp7ImJvdWdodCI6ZmFsc2UsInVubG9ja2VkIjpmYWxzZX0sIlBlYW51dCBCdXR0ZXIgTG9yZW9sIjp7ImJvdWdodCI6ZmFsc2UsInVubG9ja2VkIjpmYWxzZX0sIlJlZCBWZWx2ZXQgTG9yZW9sIjp7ImJvdWdodCI6ZmFsc2UsInVubG9ja2VkIjpmYWxzZX0sIlBlYW51dCBCdXR0ZXIgQ2hvY29sYXRlIFBpZSBMb3Jlb2wiOnsiYm91Z2h0IjpmYWxzZSwidW5sb2NrZWQiOmZhbHNlfSwiU3ByaW5nIExvcmVvbCI6eyJib3VnaHQiOmZhbHNlLCJ1bmxvY2tlZCI6ZmFsc2V9LCJEYXJrIENob2NvbGF0ZSBMb3Jlb2wiOnsiYm91Z2h0IjpmYWxzZSwidW5sb2NrZWQiOmZhbHNlfSwiQ2Fycm90IENha2UgTG9yZW9sIjp7ImJvdWdodCI6ZmFsc2UsInVubG9ja2VkIjpmYWxzZX0sIkxlbW9uIExvcmVvbCI6eyJib3VnaHQiOmZhbHNlLCJ1bmxvY2tlZCI6ZmFsc2V9LCJHb2xkZW4gTG9yZW9sIjp7ImJvdWdodCI6ZmFsc2UsInVubG9ja2VkIjpmYWxzZX0sIkNpbm5hbW9uIEJ1biBMb3Jlb2wiOnsiYm91Z2h0IjpmYWxzZSwidW5sb2NrZWQiOmZhbHNlfX19LCJzYXZlVmVyIjoxLCJkcmFnb24iOnsibGV2ZWwiOiJzeW5jIiwiYXVyYXMiOlsic3luYyIsInN5bmMiXX19O09tbmlzY2llbnQgQ29va2llczp7InNldHRpbmdzIjp7InZlcnNpb24iOiJ2Mi4zLjEiLCJhdXRvU2Nyb2xsYmFyIjp0cnVlLCJzY3JvbGxpbmdCdWlsZGluZ3MiOnRydWUsInNtb290aEJ1aWxkaW5ncyI6dHJ1ZSwiYnVmZlRvb2x0aXBEdXJhdGlvbiI6dHJ1ZSwiYmV0dGVyQnVpbGRpbmdUb29sdGlwcyI6dHJ1ZSwiYmV0dGVyR3JhbmRtYXMiOnRydWUsInNlcGFyYXRlVGVjaHMiOnRydWUsImVuaGFuY2VkQnVsayI6dHJ1ZSwiYnVpbGRpbmdzQnlwYXNzRmFuY3kiOjAsImN1cnNvcnNCeXBhc3NGYW5jeSI6MCwid3JpbmtsZXJzQnlwYXNzRmFuY3kiOjAsIm9wdGltaXplQnVpbGRpbmdzIjpmYWxzZSwicHJlc2VydmVXcmlua2xlcnMiOmZhbHNlLCJkZXRhaWxlZEN5Y2xpdXMiOnRydWUsInpvbmVkQ3ljbGl1cyI6ZmFsc2UsInRydWVDeWNsaXVzIjpmYWxzZSwic3RvY2tWYWx1ZURhdGEiOnRydWUsImRhbmdlcm91c1N0b2NrcyI6ZmFsc2UsInRvb2x0aXBXb2JibGUiOmZhbHNlLCJmYW5jeU1pbGtTZWxlY3QiOnRydWUsImltcHJvdmVNYWdpY01ldGVyIjp0cnVlLCJza3J1dWlhUmViYWxhbmNlIjpmYWxzZSwiaW1wcm92ZUFzY2VuZE1ldGVyIjp0cnVlLCJkaXNwbGF5U2Vhc29ucyI6dHJ1ZSwic2VwYXJhdGVTZWFzb25zIjpmYWxzZSwiYnJpbmdHcmFuZG1hVG9Xb3JrIjp0cnVlLCJjdXJzZWRGaW5nZXIiOmZhbHNlLCJvcHRpQ29va2llcyI6ZmFsc2UsImRhbmdlcm91c0Jyb2tlcnMiOmZhbHNlLCJoZWF2ZW5seUNvb2tpZXMiOnRydWUsImJ1aWxkaW5nUHJpY2VCdWZmIjpmYWxzZSwiZHJhd1RpbWVyRml4IjpmYWxzZSwiYWx0ZXJuYXRlU3RvY2tNYXJrZXQiOmZhbHNlLCJjb2xvcmZ1bEN1cnNvcnMiOjB9LCJzYXZlRGF0YSI6eyJ2ZXJzaW9uIjoidjIuMy4xIiwic3RvY2tBdmVyYWdlcyI6W10sImZyb3plbldyaW5rcyI6bnVsbH19O0NDU0U6eyJ2ZXJzaW9uIjoiMi4wMjEiLCJBY2hpZXZlbWVudHMiOnsiU2luZ2xlIHNpbmd1bGFyaXR5Ijp7IndvbiI6MH0sIlBlbnJvc2UgZGlhZ3JhbSI6eyJ3b24iOjB9LCJTY2h3YXJ6c2NoaWxkIjp7IndvbiI6MH0sIlByaW1vcmRpYWwgYmxhY2sgaG9sZXMiOnsid29uIjowfSwiTm8taGFpciB0aGVvcmVtIjp7IndvbiI6MH0sIlBob3RvbiBzcGhlcmUiOnsid29uIjowfSwiSW5mb3JtYXRpb24gcGFyYWRveCI6eyJ3b24iOjB9LCJHcmF2aXRhaW9uYWwgbGVuc2luZyI6eyJ3b24iOjB9LCJHYWxhY3RpYyBudWNsZWkiOnsid29uIjowfSwiU2FnaXR0YXJpdXMgQSoiOnsid29uIjowfSwiSGV5IG5vdywgeW91J3JlIGEgZGVhZCBzdGFyIjp7IndvbiI6MH0sIlJlbGF0aXZpc3RpYyBqZXRzIjp7IndvbiI6MH0sIk5ha2VkIHNpbmd1bGFyaXR5Ijp7IndvbiI6MH0sIk04NyI6eyJ3b24iOjB9LCJQeXJvdGVjaG5pY3MiOnsid29uIjowfSwiSnVseSA0dGgiOnsid29uIjowfSwiUHlyb21hbmlhYyI6eyJ3b24iOjB9LCJGdWxsIGJhcnJhZ2UiOnsid29uIjowfX0sIlVwZ3JhZGVzIjp7IkJsYWNrZXIgaG9sZXMiOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIkJsYWNrZXN0IGhvbGVzIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJWYW50YWJsYWNrIGhvbGVzIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJBZnJpY2FuLUFtZXJpY2FuIGhvbGVzIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJFdmVudCBIb3Jpem9uIENvbWljcyI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiTGFyZ2UgSGFkcm9uIENvbGxpZGVyIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJTdXBlcmNvbmR1Y3RpbmcgU3VwZXIgQ29sbGlkZXIiOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIkhhd2tpbmcgcmFkaWF0b3JzIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJNaWNybyBibGFjayBob2xlcyI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiQWNjcmV0aW9uIGRpc2NvIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJHcmF2aXRhdGlvbmFsIHdhdmVzIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJIZWF2eSBncmFuZG1hcyI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiRGFyaW5nIHBpbG90cyI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiR2VuZXJhbCByZWxhdGl2aXR5Ijp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJFeHBsb3NpdmUgYmlzY3VpdCI6eyJ1bmxvY2tlZCI6MSwiYm91Z2h0IjowfSwiUmluZyBidXJzdCI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiUGVvbnkgYnVyc3QiOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIlBhbG0gYnVyc3QiOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIkJlZXMgYnVyc3QiOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIkNyb3NzZXR0ZSBidXJzdCI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiV2F0ZXJmYWxsIGJ1cnN0Ijp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJQZWFybCBidXJzdCI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfSwiUGlzdGlsIGJ1cnN0Ijp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJTaG9ydCBmdXNlIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJTbG93IGJ1cm4iOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIkhpZ2ggZXhwbG9zaXZlIjp7InVubG9ja2VkIjowLCJib3VnaHQiOjB9LCJHcmFuZCBmaW5hbGUiOnsidW5sb2NrZWQiOjAsImJvdWdodCI6MH0sIlN0YXJidXJzdCI6eyJ1bmxvY2tlZCI6MCwiYm91Z2h0IjowfX0sIkJ1aWxkaW5ncyI6eyJCbGFjayBob2xlIGludmVydGVyIjp7ImFtb3VudCI6MCwiYm91Z2h0IjowLCJ0b3RhbENvb2tpZXMiOjAsImxldmVsIjowLCJtdXRlZCI6ZmFsc2UsIm1pbmlnYW1lU2F2ZSI6IiIsImZyZWUiOjB9fSwiQnVmZnMiOnt9LCJTZWFzb25zIjp7ImFtZXJpY2FuIjp7IlQiOi0xLCJsYXN0VGltZSI6MTYxMDc1MjM1MjUyMX19LCJPdGhlck1vZHMiOnt9fTtGb3J0dW5lIENvb2tpZTp7InNwZWxsRm9yZWNhc3RMZW5ndGgiOjEwLCJzaW1HQ3MiOjAsImNvbG9yT3ZlcnJpZGUiOnsiQnVpbGRpbmcgU3BlY2lhbCI6IiNGRjAwRkYiLCJDbGljayBGcmVuenkiOiIjNEJCOEYwIiwiRWxkZXIgRnJlbnp5IjoiI0UxQzY5OSIsIkZyZWUgU3VnYXIgTHVtcCI6IiNEQUE1NjAifSwiZm9yZWNhc3REcmFnb25Ecm9wIjp0cnVlfTtBbWVyaWNhbiBTZWFzb246eyJjb25maWciOnsiU0hPV19DQU5WQVMiOnRydWUsIkZJUkVXT1JLX0FDQ0VMRVJBVElPTiI6MS4xLCJGSVJFV09SS19CUklHSFRORVNTX01JTiI6NTAsIkZJUkVXT1JLX0JSSUdIVE5FU1NfTUFYIjo3MCwiRklSRVdPUktfU1BFRUQiOjEwLCJGSVJFV09SS19UUkFJTF9MRU5HVEgiOjMsIlNUQVJfQlJJR0hUTkVTU19NSU4iOjUwLCJTVEFSX0JSSUdIVE5FU1NfTUFYIjo4MCwiU1RBUl9DT1VOVCI6MTAwLCJTVEFSX0RFQ0FZX01JTiI6MC4wMTUsIlNUQVJfREVDQVlfTUFYIjowLjAzLCJTVEFSX0ZSSUNUSU9OIjowLjksIlNUQVJfR1JBVklUWSI6MS40LCJTVEFSX0hVRV9WQVJJQU5DRSI6MjAsIlNUQVJfVFJBTlNQQVJFTkNZIjoxLCJTVEFSX1NQRUVEX01JTiI6MiwiU1RBUl9TUEVFRF9NQVgiOjIwLCJTVEFSX1RSQUlMX0xFTkdUSCI6NSwiQ0FOVkFTX0NMRUFOVVBfQUxQSEEiOjAuMiwiSFVFX1NURVBfSU5DUkVBU0UiOjEsIlRJQ0tTX1BFUl9GSVJFV09SS19NSU4iOjUsIlNUUk9LRV9XSURUSCI6MSwiR0xPQkFMX0NPTVBPU0lURV9PUEVSQVRJT04iOiJkZWZhdWx0In0sInJvY2tldHNQb3BwZWQiOjB9O0luc3VnYXIgVHJhZGluZzp7InZlcnNpb24iOiIxLjMuMyIsInNldHRpbmdzIjp7InF1YW50aWxlc1RvRGlzcGxheSI6WzAuMjUsMC41LDAuNzVdfX07%21END%21</span></details> went from 23.3KB to 5.9KB using [lz-string](https://pieroxy.net/blog/pages/lz-string/index.html) lib (64% reduction, allegedly in under 10ms)
Just gotta import compress()/decompress() and add it before returning `JSON.stringify()` and after using `JSON.parse()`. Adds ~4KB overall in final minified bundle.
Demo: https://pieroxy.net/blog/pages/lz-string/demo.html

**Comment by TheGLander** [comment]
Just added this to the 0.3 branch, fixed by 8df958d825cb2954042c4c01d0da854fdafca6fa, thanks for the suggestion!
